Repository GTcreyon/FlashLibrary, pull requests merged in 2023-02, with the labels that each got.

#4 Reorganise navigation for games
  mkdocs.yml
Labels: enhancement

#8 Add link to the 2012 SWF
  docs/games/sm63/sm63.md
Labels: enhancement

#10 SWF bundle info
  docs/info/bundle.md
  docs/info/swf.md
  mkdocs.yml
Labels: addition

#11 Flashpoint page
  docs/players/flashpoint.md
  mkdocs.yml
Labels: addition

#12 Update ruffle.md
  docs/games/sm63/sm63.md
Labels: addition

#15 EoL page
  docs/info/eol.md
  mkdocs.yml
Labels: addition

#18 Theming
  docs/center.css
  docs/extra.css
  mkdocs.yml
Labels: css

#20 General polish and refinement
  docs/games/sm63/sm63.md
  docs/games/sm63/tas63.md
  docs/index.md
  docs/info/bundle.md
  docs/info/eol.md
  docs/info/swf.md
  docs/players/flashpoint.md
  docs/players/ngplayer.md
  docs/players/projector.md
  docs/players/ruffle.md
  docs/players/waflash.md
  docs/template.md
  docs/tools/ffdec.md
  docs/tools/riley-swf-patcher.md
  docs/tools/swf-unbundler.md
  docs/tools/swf2exe.md
Labels: rewrite
